<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Department;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coursesByDepartment = [
            'CSE' => [
                'Programming Fundamentals',
                'Object Oriented Programming',
                'Data Structures and Algorithms',
                'Database Management Systems',
                'Computer Networks',
                'Software Engineering',
                'Operating Systems',
                'Web Development',
                'Mobile Application Development',
                'Artificial Intelligence',
                'Machine Learning',
                'Computer Graphics',
                'Human Computer Interaction',
                'Cybersecurity',
                'Distributed Systems',
                'Computer Architecture',
                'Compiler Design',
                'Theory of Computation',
                'Digital Image Processing',
                'Bioinformatics',
            ],
            'EEE' => [
                'Circuit Analysis I',
                'Circuit Analysis II',
                'Digital Electronics',
                'Analog Electronics',
                'Power Systems I',
                'Power Systems II',
                'Control Systems',
                'Electromagnetic Theory',
                'Microprocessors and Microcontrollers',
                'Communications Engineering',
                'Power Electronics',
                'Signal Processing',
                'Renewable Energy Systems',
                'Electric Machines',
                'High Voltage Engineering',
                'Antenna and Wave Propagation',
                'Digital Signal Processing',
                'Power System Protection',
                'Electronic Devices and Circuits',
                'VLSI Design',
            ],
            'CE' => [
                'Engineering Mechanics',
                'Structural Analysis I',
                'Structural Analysis II',
                'Concrete Technology',
                'Steel Structures',
                'Fluid Mechanics',
                'Hydraulics',
                'Geotechnical Engineering I',
                'Geotechnical Engineering II',
                'Transportation Engineering',
                'Environmental Engineering',
                'Construction Management',
                'Highway Engineering',
                'Water Resources Engineering',
                'Earthquake Engineering',
                'Foundation Engineering',
                'Surveying',
                'Building Materials',
                'Prestressed Concrete',
                'Bridge Engineering',
            ],
            'ME' => [
                'Thermodynamics I',
                'Thermodynamics II',
                'Fluid Mechanics',
                'Heat Transfer',
                'Machine Design I',
                'Machine Design II',
                'Manufacturing Processes',
                'Industrial Engineering',
                'Mechanical Vibrations',
                'Automotive Engineering',
                'Refrigeration and Air Conditioning',
                'Power Plant Engineering',
                'Renewable Energy',
                'Robotics',
                'Mechatronics',
                'Computer Aided Design',
                'Materials Science',
                'Production Engineering',
                'Internal Combustion Engines',
                'Turbomachinery',
            ],
            'BBA' => [
                'Principles of Management',
                'Financial Accounting',
                'Management Accounting',
                'Marketing Management',
                'Human Resource Management',
                'Business Statistics',
                'Organizational Behavior',
                'Operations Management',
                'Strategic Management',
                'International Business',
                'Entrepreneurship',
                'Business Ethics',
                'Supply Chain Management',
                'Digital Marketing',
                'Investment Analysis',
                'Corporate Finance',
                'Consumer Behavior',
                'Business Communication',
                'Project Management',
                'E-commerce',
            ],
            'ECON' => [
                'Microeconomics',
                'Macroeconomics',
                'Development Economics',
                'International Economics',
                'Public Economics',
                'Labor Economics',
                'Industrial Economics',
                'Agricultural Economics',
                'Environmental Economics',
                'Health Economics',
                'Econometrics',
                'Mathematical Economics',
                'Monetary Economics',
                'Fiscal Policy',
                'Economic History',
                'Comparative Economic Systems',
                'Game Theory',
                'Behavioral Economics',
                'Financial Economics',
                'Economic Policy',
            ],
            'ELL' => [
                'English Literature I',
                'English Literature II',
                'American Literature',
                'British Literature',
                'World Literature',
                'Shakespeare Studies',
                'Modern Poetry',
                'Creative Writing',
                'Linguistics',
                'Phonetics and Phonology',
                'Syntax and Semantics',
                'Literary Criticism',
                'Comparative Literature',
                'Postcolonial Literature',
                'Women\'s Literature',
                'Contemporary Fiction',
                'Drama and Theatre',
                'Translation Studies',
                'English Language Teaching',
                'Research Methodology',
            ],
            'MATH' => [
                'Calculus I',
                'Calculus II',
                'Calculus III',
                'Linear Algebra',
                'Differential Equations',
                'Real Analysis I',
                'Real Analysis II',
                'Complex Analysis',
                'Abstract Algebra',
                'Number Theory',
                'Probability Theory',
                'Mathematical Statistics',
                'Discrete Mathematics',
                'Topology',
                'Mathematical Modeling',
                'Numerical Analysis',
                'Operations Research',
                'Graph Theory',
                'Functional Analysis',
                'Differential Geometry',
            ],
            'PHY' => [
                'Classical Mechanics',
                'Quantum Mechanics I',
                'Quantum Mechanics II',
                'Electromagnetic Theory',
                'Thermodynamics and Statistical Mechanics',
                'Solid State Physics',
                'Nuclear Physics',
                'Atomic and Molecular Physics',
                'Optics',
                'Electronics',
                'Plasma Physics',
                'Astrophysics',
                'Particle Physics',
                'Relativity',
                'Mathematical Physics',
                'Computational Physics',
                'Experimental Physics',
                'Biophysics',
                'Geophysics',
                'Medical Physics',
            ],
            'CHEM' => [
                'General Chemistry I',
                'General Chemistry II',
                'Organic Chemistry I',
                'Organic Chemistry II',
                'Inorganic Chemistry I',
                'Inorganic Chemistry II',
                'Physical Chemistry I',
                'Physical Chemistry II',
                'Analytical Chemistry',
                'Biochemistry',
                'Environmental Chemistry',
                'Industrial Chemistry',
                'Polymer Chemistry',
                'Medicinal Chemistry',
                'Quantum Chemistry',
                'Spectroscopy',
                'Electrochemistry',
                'Chemical Kinetics',
                'Thermochemistry',
                'Coordination Chemistry',
            ],
            'LAW' => [
                'Constitutional Law',
                'Criminal Law',
                'Civil Law',
                'Commercial Law',
                'International Law',
                'Administrative Law',
                'Family Law',
                'Property Law',
                'Contract Law',
                'Tort Law',
                'Labor Law',
                'Environmental Law',
                'Human Rights Law',
                'Corporate Law',
                'Tax Law',
                'Intellectual Property Law',
                'Evidence Law',
                'Jurisprudence',
                'Legal Research and Writing',
                'Alternative Dispute Resolution',
            ],
            'MED' => [
                'Anatomy',
                'Physiology',
                'Biochemistry',
                'Pathology',
                'Pharmacology',
                'Microbiology',
                'Community Medicine',
                'Forensic Medicine',
                'Internal Medicine',
                'Surgery',
                'Gynecology and Obstetrics',
                'Pediatrics',
                'Psychiatry',
                'Dermatology',
                'Ophthalmology',
                'ENT',
                'Orthopedics',
                'Radiology',
                'Emergency Medicine',
                'Medical Ethics',
            ],
        ];

        foreach ($coursesByDepartment as $departmentShortName => $courses) {
            $department = Department::where('short_name', $departmentShortName)->first();

            if ($department) {
                foreach ($courses as $courseName) {
                    Course::firstOrCreate([
                        'department_id' => $department->id,
                        'name' => $courseName,
                    ]);
                }
            }
        }
    }
}
