CREATE TABLE `submission_analyses` (
	`submission_id` text PRIMARY KEY NOT NULL,
	`run_id` text NOT NULL,
	`status` text DEFAULT 'queued' NOT NULL,
	`error` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`model` text,
	`original_bytes` integer,
	`sent_bytes` integer,
	`is_question_paper` integer,
	`paper_count` integer,
	`note` text,
	`department_id` integer,
	`department_name` text,
	`department_short_name` text,
	`course_id` integer,
	`course_name` text,
	`semester_id` integer,
	`semester_name` text,
	`exam_type_id` integer,
	`exam_type_name` text,
	`section` text,
	`batch` text,
	`raw_response` text,
	`completed_at` integer,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	FOREIGN KEY (`submission_id`) REFERENCES `submissions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`semester_id`) REFERENCES `semesters`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`exam_type_id`) REFERENCES `exam_types`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `submission_analyses_status_idx` ON `submission_analyses` (`status`);