name: Test and Deploy (Main)

on:
  push:
    branches:
      - dev
  merge_group:
    branches:
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/diuqbank
            php artisan down || true
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            git pull origin dev
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan clear-compiled
            php artisan optimize
            npm ci
            npm run build
            php artisan migrate --force
            php artisan up
